version: '3.1'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 2005Evgexa_opit28
      MYSQL_DATABASE: world
      MYSQL_USER: root

    volumes:
      - ./dbdata:/var/lib/mysql/